### ISSUE TITLE
[Question] How to deal with Kafka availability

### ISSUE THREAD

**Issue by robsontenorio** [jobcloud/php-kafka-lib#49]
This snipet won't fail even if kafka is off line (`localhost:9092`)

How to deal with that?

```php
<?php

use Jobcloud\Kafka\Message\KafkaProducerMessage;
use Jobcloud\Kafka\Producer\KafkaProducerBuilder;

$producer = KafkaProducerBuilder::create()
    ->withAdditionalBroker('localhost:9092')
    ->build();

$message = KafkaProducerMessage::create('test-topic', 0)
            ->withKey('asdf-asdf-asfd-asdf')
            ->withBody('some test message payload')
            ->withHeaders([ 'key' => 'value' ]);

$producer->produce($message);
```

**Comment by nick-zh** [comment]
Hey @robsontenorio 
For proper producer shutdown you need to call `flush` at the end (i will adjust the readme to reflect this).
Flush will not be successful and let you know about potential message loss.
`librdkafka` will retry sending the message an almost infinite amount of times. 
Alternatively you can fine tune `message.send.max.retries` and `message.timeout.ms` to get feedback sooner.

**Comment by robsontenorio** [comment]
@nick-zh Thanks for quick answer! Just saw your meetup from FWDAYS.

I am a begginer. Actually i am asking for some advices. 

More context:

- The README example code works like a charm.
- I have just shutdown kafka
- So i run `producer` code again.
- No error was thrown even with `->flush()`


I am considering a catastrophic scenario where kafka and replicas are completely offline.

- Should i have some local queue (at app boundary not kafka) before actually send it through Kafka?
- Or do we have a more elegant solution?
- Is it a best practice always to have a `local app queue` ?

**Comment by nick-zh** [comment]
You can check my example here:
https://github.com/php-kafka/php-kafka-examples/blob/main/src/ext-php-rdkafka/php-kafka-lib/producer.php
There you can see, that `flush` will return an error code. For now we are not throwing an exception, maybe this is something we could improve upon.

If you have a well managed cluster setup (maybe even with a failover cluster), you won't have any problems since Kafka is built for high availability.
The solution depends on your usecase.

Let's say you have click events, losing 1,2 is probably acceptable.
Let's say you have another event, but chance of message loss is low and not critical. Maybe you log the incident and manually send it again.
If we are talking about sensitive events, like bank account transfer event or something, you would want to build it as resilient as possible with an additional queue, checking delivery reports, etc.
It is up to you to decide how far you want to go / how much time you want to invest for your usecase.

I hope this helps :v:

**Comment by robsontenorio** [comment]
@nick-zh 

 >  For now we are not throwing an exception, maybe this is something we could improve upon.

Got it! I was expecting an exception.

Thanks for your time and general advices :)

**Comment by nick-zh** [comment]
My pleasure, have a good start into 2021 and stay safe and healthy :v:
